# Generated by Django 2.2.4 on 2019-12-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_espuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=100)),
                ('especial', models.BooleanField()),
                ('linea', models.BooleanField()),
            ],
        ),
    ]
