# Generated by Django 2.2.4 on 2019-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0002_tipo_de_espuma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizado', models.DateTimeField(auto_now=True)),
                ('nombredefecto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizado', models.DateTimeField(auto_now=True)),
                ('tipounidad', models.CharField(max_length=100)),
            ],
        ),
    ]
