# Generated by Django 2.2.4 on 2019-12-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0004_auto_20191213_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='defecto',
            name='puntuacion_de_defecto',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
