# Generated by Django 2.2.4 on 2019-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0005_defecto_puntuacion_de_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecto',
            name='puntuacion_de_defecto',
            field=models.IntegerField(default=10),
        ),
    ]
