# Generated by Django 2.2.4 on 2019-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0006_auto_20191213_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecto',
            name='puntuacion_de_defecto',
            field=models.IntegerField(),
        ),
    ]
