# Generated by Django 2.2.4 on 2019-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0007_auto_20191213_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecto',
            name='puntuacion_de_defecto',
            field=models.IntegerField(verbose_name='puntuacion del defecto'),
        ),
    ]
