# Generated by Django 2.2.4 on 2019-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0009_auto_20191213_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='defecto',
            name='imagen_tipo_defecto',
            field=models.CharField(default='https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwik5vrgurLmAhUJSK0KHZ1JCL4QjRx6BAgBEAQ&url=https%3A%2F%2Fokioki.com%2Fcollections%2Fmattresses%2Fproducts%2Fokifirm&psig=AOvVaw3os2EvgIpjUt5MiimiHw0u&ust=1576320802887346 ', max_length=500),
        ),
    ]
