# Generated by Django 2.2.4 on 2019-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0011_auto_20191213_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecto',
            name='imagen_tipo_defecto_2',
            field=models.CharField(default='https://vignette.wikia.nocookie.net/score-hero-story/images/1/15/2.jpg/revision/latest?cb=20180910160617&path-prefix=es', max_length=500),
        ),
        migrations.AlterField(
            model_name='defecto',
            name='imagen_tipo_defecto_4',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2016/06/29/16/31/numbers-1487228_960_720.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='defecto',
            name='imagen_tipo_defecto_6',
            field=models.CharField(default='https://previews.123rf.com/images/jaboy/jaboy1206/jaboy120600005/13905101-number-6-in-gold.jpg ', max_length=500),
        ),
    ]
