# Generated by Django 2.2.4 on 2019-12-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0012_auto_20191213_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defecto',
            old_name='imagen_tipo_defecto_8',
            new_name='imagen_tipo_defecto',
        ),
        migrations.RemoveField(
            model_name='defecto',
            name='imagen_tipo_defecto_2',
        ),
        migrations.RemoveField(
            model_name='defecto',
            name='imagen_tipo_defecto_4',
        ),
        migrations.RemoveField(
            model_name='defecto',
            name='imagen_tipo_defecto_6',
        ),
        migrations.AlterField(
            model_name='defecto',
            name='puntuacion_de_defecto',
            field=models.IntegerField(verbose_name='puntuacion del defecto'),
        ),
    ]
