# Generated by Django 2.2.4 on 2019-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0013_auto_20191213_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defecto',
            name='imagen_tipo_defecto',
            field=models.CharField(default='https://pbs.twimg.com/profile_images/1096162188635496449/3hAeJOKz_400x400.png ', max_length=500),
        ),
    ]
