# Generated by Django 2.2.4 on 2019-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0016_auto_20191213_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreado', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizado', models.DateTimeField(auto_now=True)),
                ('nombre_de_cliente', models.CharField(max_length=200)),
                ('tolerancia', models.IntegerField(verbose_name='Tolerancia del defecto')),
            ],
        ),
    ]
