# Generated by Django 2.2.4 on 2019-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0017_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas_de_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('largo_predef', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ancho_predef', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alto_predef', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flujo_de_aire_predef', models.IntegerField()),
                ('setting', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('extrachar', models.CharField(blank=True, max_length=200)),
                ('extrachar2', models.CharField(blank=True, max_length=200)),
                ('extrafloat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('especial', models.BooleanField()),
                ('linea', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tipo_de_espuma',
            name='especial',
        ),
        migrations.RemoveField(
            model_name='tipo_de_espuma',
            name='linea',
        ),
        migrations.AlterField(
            model_name='tipo_de_espuma',
            name='modelo',
            field=models.CharField(max_length=200),
        ),
    ]
