# Generated by Django 2.2.4 on 2019-12-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0023_auto_20191213_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='category',
            new_name='categoria',
        ),
    ]
