# Generated by Django 2.2.4 on 2019-12-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0025_remove_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
