# Generated by Django 2.2.4 on 2019-12-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0026_delete_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
