# Generated by Django 2.2.4 on 2019-12-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0028_auto_20191213_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas_de_producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
