# Generated by Django 2.2.4 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0030_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'linea'), ('2', 'especial')], default='1', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
