# Generated by Django 2.2.4 on 2019-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0031_auto_20191213_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='alto_predef',
            new_name='alto_caliente_setting_predef',
        ),
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='ancho_predef',
            new_name='ancho_caliente_setting_predef',
        ),
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='largo_predef',
            new_name='ancho_frio_predef',
        ),
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='setting',
            new_name='largo_caliente_setting_predef',
        ),
        migrations.AddField(
            model_name='medidas_de_producto',
            name='alto_frio_predef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medidas_de_producto',
            name='largo_frio_predef',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
