# Generated by Django 2.2.4 on 2019-12-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0032_auto_20191213_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_de_dimension',
            old_name='semester',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='medidas_de_producto',
            name='medida_dispobible',
            field=models.BooleanField(default=True),
        ),
    ]
