# Generated by Django 2.2.4 on 2019-12-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0033_auto_20191213_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidas_de_producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karmaapp.Categoria_de_dimension'),
        ),
    ]
