# Generated by Django 2.2.4 on 2019-12-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0034_medidas_de_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_de_dimension',
            name='categoria',
            field=models.CharField(choices=[('linea', 'linea'), ('especial', 'especial')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='medidas_de_producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='karmaapp.Categoria_de_dimension'),
        ),
    ]
