# Generated by Django 2.2.4 on 2019-12-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0036_auto_20191214_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas_de_producto',
            name='categoria',
        ),
    ]
