# Generated by Django 2.2.4 on 2019-12-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0037_remove_medidas_de_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_de_espuma',
            name='medidas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='karmaapp.Medidas_de_producto'),
        ),
    ]
