# Generated by Django 2.2.4 on 2019-12-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0038_tipo_de_espuma_medidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipo_de_espuma',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='tipo_de_espuma',
            name='creado',
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karmaapp.Figura')),
            ],
        ),
    ]
