# Generated by Django 2.2.4 on 2019-12-14 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0039_auto_20191214_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_de_espuma',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
