# Generated by Django 2.2.4 on 2019-12-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0040_tipo_de_espuma_creado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='actualizado',
            new_name='fechaactualizado',
        ),
        migrations.RenameField(
            model_name='medidas_de_producto',
            old_name='creado',
            new_name='fechacreado',
        ),
        migrations.RenameField(
            model_name='tipo_de_espuma',
            old_name='creado',
            new_name='fechacreado',
        ),
        migrations.AddField(
            model_name='tipo_de_espuma',
            name='fechaactualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
