# Generated by Django 2.2.4 on 2019-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0041_auto_20191214_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figura',
            old_name='descripcion',
            new_name='figura',
        ),
        migrations.RenameField(
            model_name='maquina',
            old_name='modelo',
            new_name='modelo_maquina',
        ),
        migrations.AddField(
            model_name='tipo_de_espuma',
            name='modelo_id',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
