# Generated by Django 2.2.4 on 2019-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0042_auto_20191214_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figura',
            old_name='figura',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='maquina',
            old_name='modelo_maquina',
            new_name='modelo',
        ),
    ]
