# Generated by Django 2.2.4 on 2019-12-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0043_auto_20191214_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='figura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karmaapp.Figura'),
        ),
    ]
